### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by Cranbaerry** [drov0/python-imagesearch#10]
Hi,

I've just recently found this from google and I am trying to make an auto clicker for an online game. The program runs fine for sometime, but after 20 minutes or so, it crashes with the following exception: 

`Process finished with exit code -1073741819 (0xC0000005)`

I have tried updating every packages, but the result is still the same. The crash happens at random times. I notice it happens when it calls "imagesearch" function so I assume there is something wrong in there. 

```
while True:
    print("Checking quest objectives")
    pos = imagesearch("images/QuestComplete_Indicator.png")
    if pos[0] != -1:
        log("Turning it to NPC")
        pos = imagesearch("images/QuestSkip_Btn.png")
        if pos[0] != -1:
            log("NPC Found")
            if pos[0] != -1:
                click_image("images/QuestSkip_Btn.png", pos, "left", 0, 0)
                time.sleep(1.5)
                pos = searchAndClickImage('images/QuestComplete_Btn.png', 0.95)
                if pos[0] != -1:
                    log("Quest completed")
                    break

        press("space")
        pos = imagesearch("images/ClickableQuest.png")
        if pos[0] != -1:
            if (customFunction is not None):
                customFunction()
            pyautogui.moveTo(pos[0] + 50, pos[1] + 3)
            click()

    time.sleep(1)
```

And this is the console log's output:

> Checking quest objectives
> Turning it to NPC
> Checking quest objectives
> Turning it to NPC
> Checking quest objectives
> Turning it to NPC
> Checking quest objectives
> Turning it to NPC
> 
> Process finished with exit code -1073741819 (0xC0000005)

**Comment by drov0** [comment]
Hello, I never ran into this issue and it isn't linked to imagesearch itself. Most likely this is linked to your installation of your python interpreter or one of the dependencies. Can you try on another computer ?

**Comment by Cranbaerry** [comment]
Hi,

You are right, apparently my codes were not thread-safe, this is my first time using PyQT to make GUI. It is now working properly, thank you.
