### ISSUE TITLE
downloading error

### ISSUE THREAD

**Issue by Jojo934** [drov0/python-imagesearch#19]
I am using the latest version of pip (20.0.2) on Windows 10 and wanted to run the installation command (pip3 install -r requirements.txt). I don't know why, but for some reason I have to use "py -m pip" instead of "pip" or "pip3", so I tried the command like that:
"py -m pip install -r requirements.txt"
and got an error message.

![73757219-32f0c700-4769-11ea-9cfa-932c07006d8f](https://user-images.githubusercontent.com/58190220/73967786-df24e000-4918-11ea-857e-e48173945f7e.PNG)

If I use "pip" or "pip3" instead of "py -m pip" and try the command like that:
"pip install -r requirements.txt"
I get an error message too.

![73757788-0b4e2e80-476a-11ea-805a-2381065e77f9](https://user-images.githubusercontent.com/58190220/73967814-eba93880-4918-11ea-8a89-8da7a88e33b5.PNG)
This message translated from German into English means:
"The command "pip" is either misspelled or could not be found."

Is there an alternative way to download the needed packages? Or do you know what I did wrong? I am very grateful for any solution or help.

 -Jojo934

**Comment by Jojo934** [comment]
I thought I solved the problem myself, but it didn't work.

**Comment by maxhambraeus** [comment]
I think you need to run the command in a folder where the requirements.txt file exists

**Comment by Jojo934** [comment]
Thanks a lot. It worked now. So this solved my problem.
