### ISSUE TITLE
Coords of 2nd image found

### ISSUE THREAD

**Issue by Mglt-b** [drov0/python-imagesearch#23]
Hello,

I need to search one image un my screen

This image can be at multiple position and can be dupplicate 

how i can get goords of this image at first position, second position, etc ?

Thanks

and thank you for you work

**Comment by drov0** [comment]
Hi, hmm this is not really possible right now with the current functions, unless you do complicated stuff with image search region.

It's relatively easily done with opencv though if you want to add a new function in the lib I'd be glad to merge it.

**Comment by Mglt-b** [comment]
Hello, ty for your answer,

I havent see this post before 
https://github.com/drov0/python-imagesearch/issues/11

Its work very nice for me
