### ISSUE TITLE
Check for is_retina opposite of intended behavior 

### ISSUE THREAD

**Issue by bws0013** [drov0/python-imagesearch#31]
When attempting to run the initial [quickstart](https://github.com/drov0/python-imagesearch/blob/master/full_examples.py#L8) example I got an error that I have tracked down to a small code issue: 

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    pos = imagesearch("./test.jpeg")
  File "/usr/local/lib/python3.8/site-packages/python_imagesearch/imagesearch.py", line 120, in imagesearch
    im.thumbnail((round(im.size[0] * 0.5), round(im.size[1] * 0.5)))
AttributeError: 'ScreenShot' object has no attribute 'thumbnail'
```

I verified the path was correct and tried using the full image path but got the same issue. Reviewing the code I noticed that the [platform check](https://github.com/drov0/python-imagesearch/blob/master/python_imagesearch/imagesearch.py#L12) for macs is being used incorrectly. 

The following if statement is run if the system is darwin and passes an output to is_retina:
```
is_retina = False
if platform.system() == "Darwin":
    is_retina = subprocess.call("system_profiler SPDisplaysDataType | grep 'retina'", shell=True)
```
The issue is that is_retina is being given the status code of the [grep operation](https://www.gnu.org/software/grep/manual/html_node/Exit-Status.html). When a grep match is found a 0 (Grep True) is returned and when nothing is found a 1 (Grep False) is returned. In the code this means that if the grep match for `retina` is found then is_retina will be set to 0 (Python False) and if it isn't found is_retina is set to 1 (Python True).

This can be fixed by modifying the is_retina assignment to be as follows:
```
is_retina = subprocess.call("system_profiler SPDisplaysDataType | grep 'retina'", shell=True) == 0
```

I have tested this on my mac successfully.

**Comment by drov0** [comment]
Thank you ! most people use the lib with windows or linux (me included) so retina support is quite lacking
