### ISSUE TITLE
imagesearch | AttributeError

### ISSUE THREAD

**Issue by anonisnap** [drov0/python-imagesearch#35]
When trying to use the imagesearch I get an AttributeError
`AttributeError: 'NoneType' object has no attribute 'shape'`
VS Code says the error is located in `imagesearch.py` on line 125, where the file reads `template.shape[::-1]`

My piece of code triggers the error
```py
import pyautogui
import python_imagesearch.imagesearch as imgSearcher

imgSearcher.imagesearch('./images/PlayAgainButton.PNG')
```

Earlier today, I downloaded python 3.9 from the Windows Store, and used pip to install python-imagesearch
I have no other versions of Python installed

**Comment by anonisnap** [comment]
Just noticed Issue #34 mentions the same problem as a comment... You can close this if you'd rather just keep it as the comment on #34

**Comment by drov0** [comment]
@AN0NISN4P Usually this means the image is not found on your system (your path is probably wrong, try with an absolute path at first). 

I have on my backlog to add a more explicit error.

**Comment by anonisnap** [comment]
If you want an update, I have found the error doesn't occur when I am running it through IDLE

**Comment by drov0** [comment]
Yeah I'm pretty sure it's linked to your path of execution since you use `./` I've pushed 1.2.0 which now raises an exception if the source image is not found which should help you debug. Closing since this seems like a user error more like a lib error.
