### ISSUE TITLE
Cant install module

### ISSUE THREAD

**Issue by msmaiaa** [drov0/python-imagesearch#39]
If i try to install the updated version it gives me this error:  
![Screenshot_10](https://user-images.githubusercontent.com/30882102/110276760-a12e3b80-7fb2-11eb-8718-de2a8cac4092.png)
But if i try to install the older version (1.2.0) it works perfectly fine
![Screenshot_11](https://user-images.githubusercontent.com/30882102/110276763-a4292c00-7fb2-11eb-838e-f8e066e32cf2.png)

**Comment by drov0** [comment]
Fixed with 1.2.2
