### ISSUE TITLE
NameError: name 'r' is not defined

### ISSUE THREAD

**Issue by ghost** [drov0/python-imagesearch#4]
When I try to click on an image I get this error message on the click_image function
 ```
pyautogui.moveTo(pos[0] + r(width / 2, offset), pos[1] + r(height / 2,offset), timestamp)
NameError: name 'r' is not defined
```

**Comment by drov0** [comment]
Mmmh odd, r is defined at the end of the file, I'll make some tests this week. Are you sure you don't have a variable named r somewhere ?

**Comment by ghost** [comment]
Problem fixed, I didn't see there a function called r at the end of the file

**Comment by drov0** [comment]
Neat :)
