### ISSUE TITLE
with open('requirements.txt') as f:     FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by vypr** [drov0/python-imagesearch#42]
hello, i got this problem on windows and Ubuntu,  i resolved it by manually downloading the tar and copying the  python_imagesearch.egg-info/requires.txt to where setup.py is placed and renaming it as requirements.txt.

**Comment by vincenthavinh** [comment]
Thank you for your solution @vypr ,
this issue prevented me from installing latest 1.2.1 version with `pip install python-imagesearch`.

**Comment by culcube** [comment]
I have had this problem before, in #27

I had exactly this problem again with python-imagesearch-1.2.1.tar.gz but python_imagesearch-1.2.0-py3-none-any.whl worked ok.

**Comment by vypr** [comment]
> Thank you for your solution @vypr , this issue prevented me from installing latest 1.2.1 version with `pip install python-imagesearch`.

hello, i just saw your reply, glad i could help

**Comment by boredland** [comment]
there has to be a better solution. isn't this just a borked release of some kind?

**Comment by drov0** [comment]
Sorry about the delay, it was indeed a borked release, this should work now on 1.2.2.

Feel free to reopen if you still encounter this issue.
