### ISSUE TITLE
Way to turn down minimum resemblance?

### ISSUE THREAD

**Issue by Z-Coder2100** [drov0/python-imagesearch#47]
When image scanning, it uses a system to check if it looks somewhat alike, is there a way to make it more strict? My images are very similar.

Thanks!
![notgo](https://user-images.githubusercontent.com/92608975/177200768-8a37c280-79ab-46f7-8bf2-f51602ea4487.png)
![go](https://user-images.githubusercontent.com/92608975/177200770-0705d2d7-db18-4404-90f8-937cdfd6162e.png)

**Comment by eagleEggs** [comment]
There is a precision parameter within the search functions you can utilize. Set precision=1.
