### ISSUE TITLE
include macOS install instruction

### ISSUE THREAD

**Issue by dimirey** [drov0/python-imagesearch#5]
Would it be possible to include macOS install instruction?

Thanks

**Comment by drov0** [comment]
Hello, 

I do not have a mac but I'll try to get my hands on one to add them :)

**Comment by kraftydevil** [comment]
Any word on adding mac installs?

There are ways to install apt-get on a mac, but it's not recommended to use it alongside an existing package manager. I'm already using Homebrew for quite a few things.

I'd really like to use this.

**Comment by drov0** [comment]
Alright I'm get to work on this, I'll add the instructions today or tomorrow.

**Comment by drov0** [comment]
Actually I still don't have a macos environment, but I can definitely guide you through the install  @kraftydevil  

You need those components : 

cv2 (opencv) : 

https://medium.com/@nuwanprabhath/installing-opencv-in-macos-high-sierra-for-python-3-89c79f0a246a

Looks like `brew install opencv` works 

pyautogui : 

As per the ![documentation](https://github.com/asweigart/pyautogui) : 
"OS X needs the pyobjc-core and pyobjc module installed in that order"

So it's an easy 
`pip3 install -U pyobjc-core`
`pip3 install -U pyobjc`

Also note that if you are using mojave you may need to change your config : https://github.com/asweigart/pyautogui/issues/247

"Not a pyautogui user, but on Mojave, there's a new security feature where you must explicitly allow applications to use your mouse/keyboard. Have a look in Security Preferences > Security & Privacy > Privacy > Accessibility - you might have to allow your terminal application in the list."

Once you have those try 

`pip3 install -r requirements.txt`

 and see if you have errors.  If this worked, please report back so I can update the README

**Comment by kraftydevil** [comment]
No install errors 👍- using 10.13.6 (High Sierra).

Install was as you mentioned:
```
brew install opencv
pip3 install -U pyobjc-core
pip3 install -U pyobjc
git clone https://github.com/drov0/python-imagesearch.git
cd python-imagesearch
pip3 install -r requirements.txt
```

I will test with one of the examples and report back.

**Comment by kraftydevil** [comment]
yep, the first two examples are working 👍. Thanks for guiding me to it.

**Comment by drov0** [comment]
Awesome, thanks !

**Comment by Zodor** [comment]
I have followed the install instructions on my Mac, but I am getting this

```
          Display Type: Built-in Liquid Retina XDR Display
          Resolution: 3456 x 2234 Retina
Traceback (most recent call last):
  File "M.py", line 16, in <module>
    pos = imagesearch(sys.argv[1])
  File "myenv/lib/python3.13/site-packages/python_imagesearch/imagesearch.py", line 124, in imagesearch
    im.thumbnail((round(im.size[0] * 0.5), round(im.size[1] * 0.5)))
    ^^^^^^^^^^^^
AttributeError: 'ScreenShot' object has no attribute 'thumbnail'
```

**Comment by phongtnit** [comment]
> I have followed the install instructions on my Mac, but I am getting this
> 
> ```
>           Display Type: Built-in Liquid Retina XDR Display
>           Resolution: 3456 x 2234 Retina
> Traceback (most recent call last):
>   File "M.py", line 16, in <module>
>     pos = imagesearch(sys.argv[1])
>   File "myenv/lib/python3.13/site-packages/python_imagesearch/imagesearch.py", line 124, in imagesearch
>     im.thumbnail((round(im.size[0] * 0.5), round(im.size[1] * 0.5)))
>     ^^^^^^^^^^^^
> AttributeError: 'ScreenShot' object has no attribute 'thumbnail'
> ```

I had the same runtime error.
