### ISSUE TITLE
finding coordinates of multiple images on display

### ISSUE THREAD

**Issue by gtxaspec** [drov0/python-imagesearch#9]
Hello, 

using the sample in example.py, you run a check for multiple images on the screengrab (im), but it does not return the coordinates of the matches.  

should imagesearcharea return the coordinates or is this not possible?

for example:

i have 5 possibles images that i would like matches to the screen,
return the coordinates when 1 of the 5 is found.

thank you!

**Comment by drov0** [comment]
Hello, you can only search for one image at a time, so you would need to perform 5 imagesearch, the last example shows how to do that : 

You just need to add variables in front of the imagesearcharea to get the positions

```

im = region_grabber((0, 0, 800, 600))
pos1 = imagesearcharea("./github.png", 0, 0, 800, 600, 0.8, im)
pos2 = imagesearcharea("./panda.png", 0, 0, 800, 600, 0.8, im)
pos3 = imagesearcharea("./panda.png", 0, 0, 800, 600, 0.8, im)
pos4 = imagesearcharea("./panda.png", 0, 0, 800, 600, 0.8, im)
pos5 = imagesearcharea("./panda.png", 0, 0, 800, 600, 0.8, im)
```

And then see which of the 5 positions isn't equal to -1 and return that position
